import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { pathToFileURL } from "node:url";
import { build } from "esbuild";
import { loadApps, projectRoot, read } from "./lib/project.mjs";
import { scopeAppStyles } from "./lib/css.mjs";

const banner = "Generated by npm run build. Edit src/, not this file.";

/** Produce deployment bytes in memory first: --check never modifies the checkout. */
export async function compileSite(root = projectRoot) {
    const apps = await loadApps(root);
    const imports = apps.map((app, i) => `import app${i} from "./${app.source}/controller.js";`).join("\n");
    const entry = `${imports}
import { startShell } from "./src/shell/start.js";
startShell(window.ANSON_APP_MANIFEST, { ${apps.map((app, i) => `${JSON.stringify(app.id)}: app${i}`).join(", ")} }, window.ANSON_SHELL_ICONS);`;
    const js = await build({
        absWorkingDir: root,
        stdin: { contents: entry, resolveDir: root, sourcefile: "generated-entry.js" },
        bundle: true,
        format: "iife",
        target: "es2022",
        charset: "utf8",
        sourcemap: "linked",
        sourcesContent: false,
        outfile: path.join(root, "main.js"),
        write: false,
        metafile: true,
        banner: { js: `/* ${banner} */` },
        logLevel: "silent",
    });
    const outputs = new Map(js.outputFiles.map((file) => [path.basename(file.path), file.text]));
    const concatenate = async (files) =>
        `/* ${banner} */\n` +
        (
            await Promise.all(
                files.map(async (file) => {
                    const css = await read(root, file);
                    const appId = file.match(/^src\/apps\/([^/]+)\//)?.[1];
                    return `\n/* Source: ${file} */\n${appId ? scopeAppStyles(css, appId) : css}`;
                }),
            )
        ).join("\n");
    outputs.set(
        "style.css",
        await concatenate(["src/shell/styles/base.css", ...apps.map((app) => `${app.source}/styles.css`)]),
    );
    outputs.set(
        "macos.css",
        await concatenate(["src/shell/styles/theme.css", ...apps.map((app) => `${app.source}/window.css`)]),
    );
    for (const file of ["dock.css", "icons.css"])
        outputs.set(file, await concatenate([`src/shell/styles/${file}`]));
    const shellIcons = JSON.parse(await read(root, "src/shell/icons.json"));
    const manifest = apps.map(({ source: _source, ...app }) => app);
    outputs.set(
        "apps.config.js",
        `/* ${banner} */
(function () {
    "use strict";
    const freeze = value => {
        if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); }
        return value;
    };
    window.ANSON_APP_MANIFEST = freeze(${JSON.stringify(manifest, null, 4)});
    window.ANSON_SHELL_ICONS = freeze(${JSON.stringify(shellIcons, null, 4)});
})();
`,
    );
    const html = await read(root, "src/shell/index.html");
    if (html.split("{{APP_WINDOWS}}").length !== 2)
        throw new Error("Shell HTML needs exactly one {{APP_WINDOWS}} mount");
    const windows = await Promise.all(
        apps.map(
            async (app) =>
                `<!-- App source: ${app.source}/view.html -->\n${await read(root, `${app.source}/view.html`)}`,
        ),
    );
    const earlyApps = [];
    for (const app of apps) {
        if (await fs.stat(path.join(root, app.source, "early.js")).catch(() => null)) earlyApps.push(app);
    }
    const early = await build({
        absWorkingDir: root,
        stdin: {
            contents: earlyApps
                .map(
                    (app, i) =>
                        `import prepare${i} from "./${app.source}/early.js";\nprepare${i}({ getRoot: () => document.querySelector('[data-window="${app.id}"]') });`,
                )
                .join("\n"),
            resolveDir: root,
            sourcefile: "generated-early.js",
        },
        bundle: true,
        format: "iife",
        target: "es2022",
        charset: "utf8",
        write: false,
        metafile: true,
        logLevel: "silent",
    });
    const assembled = html
        .replace("{{APP_WINDOWS}}", windows.join("\n"))
        .replace("{{APP_EARLY_SCRIPTS}}", early.outputFiles[0].text);
    const hash = createHash("sha256").update(assembled);
    for (const [file, contents] of [...outputs].sort(([a], [b]) => a.localeCompare(b)))
        hash.update(file).update(contents);
    const version = `build-${hash.digest("hex").slice(0, 12)}`;
    outputs.set(
        "index.html",
        assembled
            .replace("<!DOCTYPE html>", `<!DOCTYPE html>\n<!-- ${banner} -->`)
            .replaceAll("{{BUILD_VERSION}}", version),
    );
    outputs.set(
        "site.build.json",
        JSON.stringify(
            {
                schemaVersion: 1,
                version,
                apps: apps.map(({ id, appLabel, source }) => ({ id, label: appLabel, source })),
            },
            null,
            2,
        ) + "\n",
    );
    const rows = await Promise.all(
        apps.map(async (app) => {
            const files = await fs.readdir(path.join(root, app.source));
            const links = [
                "manifest.json",
                "view.html",
                "controller.js",
                "styles.css",
                "window.css",
                ...files.filter((file) => /^(?:content\.(?:json|js)|early\.js)$/.test(file)),
            ];
            return `| ${app.appLabel.replaceAll("|", "\\|")} | \`#${app.id}\` | [App 說明](../${app.source}/README.md) | ${links.map((file) => `[${file}](../${app.source}/${file})`).join(" · ")} |`;
        }),
    );
    outputs.set(
        "knowledge/apps.md",
        `# App 維護索引\n\n<!-- ${banner} -->\n\n由各 App manifest 自動生成；新增或刪除 App 後執行 \`npm run build\`。回到[維護地圖](map.md)。\n\n| App | 深層入口 | 維護說明 | 來源 |\n| --- | --- | --- | --- |\n${rows.join("\n")}\n`,
    );
    return {
        outputs,
        version,
        apps,
        metafile: { inputs: { ...js.metafile.inputs, ...early.metafile.inputs } },
    };
}

export async function buildSite({ root = projectRoot, check = false } = {}) {
    const result = await compileSite(root);
    const stale = [];
    for (const [file, contents] of result.outputs) {
        const current = await read(root, file).catch(() => null);
        if (current === contents) continue;
        if (check) stale.push(file);
        else {
            await fs.mkdir(path.dirname(path.join(root, file)), { recursive: true });
            await fs.writeFile(path.join(root, file), contents);
        }
    }
    if (stale.length) throw new Error(`Generated files are stale: ${stale.join(", ")}. Run npm run build.`);
    return result;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
    const check = process.argv.includes("--check");
    const result = await buildSite({ check });
    console.log(
        `${check ? "Build verified" : "Built"}: ${result.apps.length} Apps, ${result.outputs.size} deployment files, ${result.version}`,
    );
}
